//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap(Locale.init) ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)
  
  static func validate() throws {
    try intern.validate()
  }
  
  /// This `R.color` struct is generated, and contains static references to 0 colors.
  struct color {
    fileprivate init() {}
  }
  
  /// This `R.file` struct is generated, and contains static references to 0 files.
  struct file {
    fileprivate init() {}
  }
  
  /// This `R.font` struct is generated, and contains static references to 0 fonts.
  struct font {
    fileprivate init() {}
  }
  
  /// This `R.image` struct is generated, and contains static references to 0 images.
  struct image {
    fileprivate init() {}
  }
  
  /// This `R.nib` struct is generated, and contains static references to 5 nibs.
  struct nib {
    /// Nib `ChatInputBottomView`.
    static let chatInputBottomView = _R.nib._ChatInputBottomView()
    /// Nib `ClovaSpeechListCell`.
    static let clovaSpeechListCell = _R.nib._ClovaSpeechListCell()
    /// Nib `DmMyChatViewCell`.
    static let dmMyChatViewCell = _R.nib._DmMyChatViewCell()
    /// Nib `DmPostCell`.
    static let dmPostCell = _R.nib._DmPostCell()
    /// Nib `DmYourChatViewCell`.
    static let dmYourChatViewCell = _R.nib._DmYourChatViewCell()
    
    /// `UINib(name: "ChatInputBottomView", in: bundle)`
    static func chatInputBottomView(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.chatInputBottomView)
    }
    
    /// `UINib(name: "ClovaSpeechListCell", in: bundle)`
    static func clovaSpeechListCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.clovaSpeechListCell)
    }
    
    /// `UINib(name: "DmMyChatViewCell", in: bundle)`
    static func dmMyChatViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.dmMyChatViewCell)
    }
    
    /// `UINib(name: "DmPostCell", in: bundle)`
    static func dmPostCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.dmPostCell)
    }
    
    /// `UINib(name: "DmYourChatViewCell", in: bundle)`
    static func dmYourChatViewCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.dmYourChatViewCell)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.reuseIdentifier` struct is generated, and contains static references to 4 reuse identifiers.
  struct reuseIdentifier {
    /// Reuse identifier `ClovaSpeechListCell`.
    static let clovaSpeechListCell: Rswift.ReuseIdentifier<ClovaSpeechListCell> = Rswift.ReuseIdentifier(identifier: "ClovaSpeechListCell")
    /// Reuse identifier `DmPostCell`.
    static let dmPostCell: Rswift.ReuseIdentifier<DmPostCell> = Rswift.ReuseIdentifier(identifier: "DmPostCell")
    /// Reuse identifier `DmYourChatViewCell`.
    static let dmYourChatViewCell: Rswift.ReuseIdentifier<DmYourChatViewCell> = Rswift.ReuseIdentifier(identifier: "DmYourChatViewCell")
    /// Reuse identifier `MyChat`.
    static let myChat: Rswift.ReuseIdentifier<DmMyChatViewCell> = Rswift.ReuseIdentifier(identifier: "MyChat")
    
    fileprivate init() {}
  }
  
  /// This `R.segue` struct is generated, and contains static references to 0 view controllers.
  struct segue {
    fileprivate init() {}
  }
  
  /// This `R.storyboard` struct is generated, and contains static references to 4 storyboards.
  struct storyboard {
    /// Storyboard `AddClovaViewController`.
    static let addClovaViewController = _R.storyboard.addClovaViewController()
    /// Storyboard `ClovaSpeechList`.
    static let clovaSpeechList = _R.storyboard.clovaSpeechList()
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()
    /// Storyboard `TopViewController`.
    static let topViewController = _R.storyboard.topViewController()
    
    /// `UIStoryboard(name: "AddClovaViewController", bundle: ...)`
    static func addClovaViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.addClovaViewController)
    }
    
    /// `UIStoryboard(name: "ClovaSpeechList", bundle: ...)`
    static func clovaSpeechList(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.clovaSpeechList)
    }
    
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    
    /// `UIStoryboard(name: "TopViewController", bundle: ...)`
    static func topViewController(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.topViewController)
    }
    
    fileprivate init() {}
  }
  
  /// This `R.string` struct is generated, and contains static references to 0 localization tables.
  struct string {
    fileprivate init() {}
  }
  
  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }
    
    fileprivate init() {}
  }
  
  fileprivate class Class {}
  
  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    try nib.validate()
  }
  
  struct nib: Rswift.Validatable {
    static func validate() throws {
      try _DmYourChatViewCell.validate()
    }
    
    struct _ChatInputBottomView: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "ChatInputBottomView"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }
      
      fileprivate init() {}
    }
    
    struct _ClovaSpeechListCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = ClovaSpeechListCell
      
      let bundle = R.hostingBundle
      let identifier = "ClovaSpeechListCell"
      let name = "ClovaSpeechListCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> ClovaSpeechListCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? ClovaSpeechListCell
      }
      
      fileprivate init() {}
    }
    
    struct _DmMyChatViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = DmMyChatViewCell
      
      let bundle = R.hostingBundle
      let identifier = "MyChat"
      let name = "DmMyChatViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> DmMyChatViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? DmMyChatViewCell
      }
      
      fileprivate init() {}
    }
    
    struct _DmPostCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType {
      typealias ReusableType = DmPostCell
      
      let bundle = R.hostingBundle
      let identifier = "DmPostCell"
      let name = "DmPostCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> DmPostCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? DmPostCell
      }
      
      fileprivate init() {}
    }
    
    struct _DmYourChatViewCell: Rswift.NibResourceType, Rswift.ReuseIdentifierType, Rswift.Validatable {
      typealias ReusableType = DmYourChatViewCell
      
      let bundle = R.hostingBundle
      let identifier = "DmYourChatViewCell"
      let name = "DmYourChatViewCell"
      
      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [NSObject : AnyObject]? = nil) -> DmYourChatViewCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? DmYourChatViewCell
      }
      
      static func validate() throws {
        if UIKit.UIImage(named: "Image", in: R.hostingBundle, compatibleWith: nil) == nil { throw Rswift.ValidationError(description: "[R.swift] Image named 'Image' is used in nib 'DmYourChatViewCell', but couldn't be loaded.") }
      }
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  struct storyboard {
    struct addClovaViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = AddClovaViewController
      
      let bundle = R.hostingBundle
      let name = "AddClovaViewController"
      
      fileprivate init() {}
    }
    
    struct clovaSpeechList: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = ClovaSpeechListViewController
      
      let bundle = R.hostingBundle
      let name = "ClovaSpeechList"
      
      fileprivate init() {}
    }
    
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = UIKit.UIViewController
      
      let bundle = R.hostingBundle
      let name = "LaunchScreen"
      
      fileprivate init() {}
    }
    
    struct topViewController: Rswift.StoryboardResourceWithInitialControllerType {
      typealias InitialController = TopViewController
      
      let bundle = R.hostingBundle
      let name = "TopViewController"
      
      fileprivate init() {}
    }
    
    fileprivate init() {}
  }
  
  fileprivate init() {}
}
